version: '2'
services:
  mgr.node3.ceph.wator.xyz:
    image: ceph/daemon
    network_mode: "host"
    volumes:
      - /ceph/conf/etc:/etc/ceph
      - /ceph/conf/ganesha:/etc/ganesha
      - /ceph/storage1/mon:/var/lib/ceph
    command: mgr
    restart: 'no'
