version: '3'
services:
  mon:
    image: ceph/daemon
    hostname: node3.ceph.wator.xyz
    volumes:
      - /ceph/master/deploy/etc:/etc/ceph
      - /ceph/master/deploy/ceph:/var/lib/ceph
      - /ceph/master/deploy/log:/var/log/ceph
    environment:
      - MON_NAME=node3.ceph.wator.xyz
      - MON_IP=[2400:2412:13e0:9d00:2ce:39ff:fece:132]
      - CEPH_PUBLIC_NETWORK=2400:2412:13e0:9d00::/64
      - CEPH_CLUSTER_NETWORK=2400:2412:13e0:9d00::/64
    command: mon
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 256M    
  mds3:
    image: ceph/daemon
    hostname: node3.ceph.wator.xyz
    volumes:
      - /ceph/master/deploy/etc:/etc/ceph
      - /ceph/master/deploy/ceph:/var/lib/ceph
      - /ceph/master/deploy/log:/var/log/ceph
    environment:
      - MDS_NAME=node3.ceph.wator.xyz
      - CEPHFS_CREATE=1
    command: mds
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 256M    

  mgr:
    image: ceph/daemon
    hostname: node3.ceph.wator.xyz
    volumes:
      - /ceph/master/deploy/etc:/etc/ceph
      - /ceph/master/deploy/ceph:/var/lib/ceph
      - /ceph/master/deploy/log:/var/log/ceph
    command: mgr
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 256M    
    
networks:
  outside:
    external:
      name: "host"


