version: '2'
services:
  mds2.node3.ceph.wator.xyz:
    image: ceph/daemon
    network_mode: "host"
    volumes:
      - /ceph/conf/etc:/etc/ceph
      - /ceph/conf/ganesha:/etc/ganesha
      - /ceph/storage1/mon:/var/lib/ceph
      - /ceph/storage1/log:/var/log/ceph/
    environment:
      - MDS_NAME=mds2.node2.ceph.wator.xyz
      - CEPHFS_CREATE=1
    command: mds
    restart: 'always'
